### ISSUE TITLE
Make it easier to discover how LAN traffic is allowed/blocked

### ISSUE THREAD

**Issue by Ghostkeeper** [ivpn/desktop-app-cli#1]
# Feature request

Could you make it easier to figure out how to allow LAN traffic?

## Description

Today I installed your application and found that I couldn't reach the file server in my LAN any more. Since I had just installed it a minute earlier I realised that it would be IVPN, and went looking for that in the `-h` information in the CLI application. I saw that "Allow LAN" was set to "false" but couldn't find how to make it "true".

I looked for it here in your source code and found that this was part of the firewall configuration. I needed to call `ivpn firewall -lan-allow` and then apparently `ivpn firewall -off` and `ivpn firewall -on` to make that change go into effect.

Not everyone has the knowledge to dig through the source code to find it, nor the intelligence that this feature could be part of the firewall.

## Describe the solution you'd like

I'd like to ask you to give this configuration a more prominent place in the `-h` command. Perhaps you could add it to the tips?

## Describe alternatives you've considered

You could also move this configuration outside of the firewall settings altogether, though that may not make sense for developing. Initially I was looking for a command like `ivpn config`.
Or you could supply some complete documentation on the IVPN website through which I could search for the keyword "LAN".

**Comment by stenya** [comment]
Hi @Ghostkeeper 
thank for your interest in our project.

To enable LAN communication it is enough to call   
`ivpn firewall -lan-allow`. The changes will be applied immediately.
Not needed to reconnect firewall (`ivpn firewall -off / ivpn firewall -on`)

The information about these commands is already in the `-h` for an `antitracker` command:
`ivpn antitracker -h`; same info you can see by calling `ivpn -h -full` 
```
$ ivpn firewall -h
Command usage:
firewall      Firewall management
  -status     - (default) Show info about current firewall status
  -lan_allow  - Set configuration: allow LAN communication (take effect when firewall enabled)
  -lan_block  - Set configuration: block LAN communication (take effect when firewall enabled)
  -off        - Switch-off firewall
  -on         - Switch-on firewall
```

According to the information above, are you still want to add tips regarding `firewall -lan_allow` command?

**Comment by Ghostkeeper** [comment]
Ah, I didn't know about `-h -full`. That is mentioned in the tips, in fact, and could be considered good enough. Maybe I was just unlucky or didn't read well enough.

I was merely suggesting making that a bit more discoverable because not knowing the implementation, I wouldn't have guessed that this would be under "firewall".

Happy to help testing! The client has been stable so far, for me.
