### ISSUE TITLE
Having to log-in manually after each update

### ISSUE THREAD

**Issue by pilsnerbeer** [ivpn/desktop-app-cli#2]
# Bug report

## Describe your environment

* Device: _____  desktop
* OS name and version: _____  ubuntu 20.04
* IVPN app version: _____  2.12.1

## Describe the problem
Have to log-in via 'ivpn login' after each update. As the updates come, it's getting increasingly annoying.

**Comment by stenya** [comment]
Thank you for the report and your interest in our project.
We will try to solve this problem in future releases.

**Comment by Ghostkeeper** [comment]
Interestingly, it did remember the last server I connected to (through `ivpn connect -last`).
But it also forgot the "Allow LAN" configuration I had.

**Comment by stenya** [comment]
Thanks. I will take a look at it.

**Comment by stenya** [comment]
@pilsnerbeer v2.12.3 released.
The application will stay logged-in on each future update.
Note: this will work only when upgrading from v2.12.3

**Comment by stenya** [comment]
@Ghostkeeper The last "Allow LAN" configuration is saved on the service side.
Calling `ivpn firewall -on` or `ivpn connect -last` will use the last used 'Allow LAN' value automatically.
