### ISSUE TITLE
Packaging for Arch Linux (Arch User Repository)

### ISSUE THREAD

**Issue by gaalcaras** [ivpn/desktop-app-cli#3]
# Feature request

## Description

I'm trying to package the ivpn cli interface for Arch Linux.

## Describe the solution you'd like

The way AUR packages usually work is by pulling the sources and compiling from scratch. I'm having a hard time doing that manually on Arch Linux. Everything seems to compile just fine (daemon and cli both), but I fail to see how to launch the daemon as a service. How do I use the the `ivpn-service` executable? Do I have to set up a systemd unit service or something? Any feedback on this would be greatly appreciated.

**Comment by stenya** [comment]
Hi @gaalcaras 

ivpn-service is checking to exist of some required files. All files can be found in the repository.

```
VirtualBox:/opt/ivpn/etc$ ls -l
total 52
-r-------- 1 root root  2358 May 25 16:50 ca.crt
-rwx------ 1 root root   113 May 25 16:50 client.down
-rwx------ 1 root root  1927 May 25 16:50 client.up
-rwx------ 1 root root  5224 May 25 16:50 firewall.sh
-rw------- 1 root root 21524 May 26 20:52 servers.json
-r-------- 1 root root   451 May 25 16:50 signing.pub
-r-------- 1 root root   636 May 25 16:50 ta.key
```

If you want to install IVPN service manually, the next steps are required:

1. Create folder `/opt/ivpn/etc`
2. Copy all required files (see above). Note: Files owner and access rights are important!
3. Now you can start compiled service binary from the command line (just to check if it works). Note: The service must be started under a privileged user!
3.1. Simply run compiled ivpn-cli binary to check if it successfully connects to the service (use separate terminal).
4. If everything works - you can configure your environment to start ivpn-service automatically with the system boot. We are using systemd for such purposes.

Note!: 
The logging is disabled by default in the current version of ivpn-service.  Unfortunately, this means that there is no chance to check the logs if there any issues of service start. 
The new version (which we plan to release the nearest time) will have the possibility to enable service logging manually by the command line parameter.

**Comment by gaalcaras** [comment]
Thanks for the great feedback, I've successfully managed to get everything to run by getting the permissions just right.

Unfortunately, I still have trouble connecting to a server, see #5 .

I will package the ipvn client for ArchLinux once I get everything running smoothly on my own machine ;-)

**Comment by gaalcaras** [comment]
Quick update to let you guys know that the IVPN command line tool is now available for Arch Linux on the AUR: https://aur.archlinux.org/packages/ivpn-git/

Happy to see IVPN go the open source route!

**Comment by stenya** [comment]
Wow! 
That is awesome.
Thank you @gaalcaras  !

**Comment by stenya** [comment]
Hi @gaalcaras 

the official IVPN packages are available on AUR:
https://aur.archlinux.org/packages/ivpn/
https://aur.archlinux.org/packages/ivpn-ui/

You can take it as an example to update your git-based repo 'ivpn-git'.
There are unnecessary dependencies from: 'fpm' and 'rpm-tools'.
One required dependency is missing: 'wireless_tools'.
