### ISSUE TITLE
Error: failed to connect: failed to change firewall state

### ISSUE THREAD

**Issue by gaalcaras** [ivpn/desktop-app-cli#5]
# Bug report

## Describe your environment

* Device: Thinkpad X1 Extreme  
* OS name and version: ArchLinux 
* IVPN app version: 2.12.3 (date:2020-06-13 commit:025fdcddb2e7b61c525fb8330d668094d8bd50b9)  

### Steps to reproduce:

Try to connect to any server. I get the same error with a variation of commands (`-fastest`) and with both OpenVPN and Wireguard. Same error with `ivpn firewall -on`.

### Observed Results:

I get this error message:

`Error: failed to connect: failed to change firewall state : failed to execute shell command: exit status 3`

For instance, `ivpn connect ch.wg.ivpn.net` gives:

```
[WireGuard] Connecting to: Zurich, CH (Switzerland) ch.wg.ivpn.net UDP:2049...
Connecting...
Disconnecting...
Error: failed to connect: failed to change firewall state : failed to execute shell command: exit status 3
```

I checked the logs but they're completely empty.

### Expected Results:

Connect to a server :)

**Comment by stenya** [comment]
The firewall functionality for Linux is based on 'iptables'.
Probably there is a problem executing `iptables` command on your device.
I will try to analyze the issue in detail. 

Meanwhile, you can check if it works without a firewall.
Just use `-fw_off` flag with `connect` command.
See details` ivpn connect -h`.  (to enable logs: `ivpn logs -on`)

**Comment by gaalcaras** [comment]
Uh, I tried with `-fw_off` and it worked, but now for some reason it is working fine even with the firewall on. Unfortunately, I didn't enable the logs the first time around, so I can't provide them.

I'll close the issue for now and I'll come back to it if I run into this issue again in the future.
